# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_generator_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("background-color: #FFFFFF;")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 421, 71))
        self.frame.setStyleSheet("background-color: #45bd5b;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(430, 10, 51, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("img/icon.png"))
        self.label_4.setObjectName("label_4")
        self.le_length = QtWidgets.QLineEdit(self.centralwidget)
        self.le_length.setGeometry(QtCore.QRect(240, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.le_length.setFont(font)
        self.le_length.setAlignment(QtCore.Qt.AlignCenter)
        self.le_length.setObjectName("le_length")
        self.te_result = QtWidgets.QTextEdit(self.centralwidget)
        self.te_result.setGeometry(QtCore.QRect(300, 80, 191, 201))
        self.te_result.setLineWrapColumnOrWidth(0)
        self.te_result.setReadOnly(True)
        self.te_result.setObjectName("te_result")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.le_count = QtWidgets.QLineEdit(self.centralwidget)
        self.le_count.setGeometry(QtCore.QRect(240, 110, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.le_count.setFont(font)
        self.le_count.setAlignment(QtCore.Qt.AlignCenter)
        self.le_count.setObjectName("le_count")
        self.cb_use_numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_use_numbers.setGeometry(QtCore.QRect(10, 140, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.cb_use_numbers.setFont(font)
        self.cb_use_numbers.setChecked(True)
        self.cb_use_numbers.setObjectName("cb_use_numbers")
        self.cb_use_letters = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_use_letters.setGeometry(QtCore.QRect(10, 170, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.cb_use_letters.setFont(font)
        self.cb_use_letters.setChecked(True)
        self.cb_use_letters.setObjectName("cb_use_letters")
        self.cb_use_punctuation = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_use_punctuation.setGeometry(QtCore.QRect(10, 200, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.cb_use_punctuation.setFont(font)
        self.cb_use_punctuation.setChecked(True)
        self.cb_use_punctuation.setObjectName("cb_use_punctuation")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #45bd5b;")
        self.pushButton.setObjectName("pushButton")
        self.frame.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.le_length.raise_()
        self.te_result.raise_()
        self.label_5.raise_()
        self.le_count.raise_()
        self.cb_use_numbers.raise_()
        self.cb_use_letters.raise_()
        self.cb_use_punctuation.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор паролей"))
        self.label_2.setText(_translate("MainWindow", "Длина пароля (до 100):"))
        self.label_3.setText(_translate("MainWindow", "ГЕНЕРАТОР ПАРОЛЕЙ"))
        self.le_length.setText(_translate("MainWindow", "10"))
        self.te_result.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Результат генерации паролей</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Количество паролей (до 100):"))
        self.le_count.setText(_translate("MainWindow", "10"))
        self.cb_use_numbers.setText(_translate("MainWindow", "Использовать цифры"))
        self.cb_use_letters.setText(_translate("MainWindow", "Использовать латинские буквы"))
        self.cb_use_punctuation.setText(_translate("MainWindow", "Использовать спецсимволы"))
        self.pushButton.setText(_translate("MainWindow", "СГЕНЕРИРОВАТЬ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
